### ISSUE TITLE
Add "Invite tenants to a building" functionality to BuildingManager

### ISSUE THREAD

**Issue by MBarjaktarovic** [execom-eu/building_manager#6]
Add `InviteTenantToBuildingCommand` to `BulidingManager` and the `TenantInvitedToBuildingEvent` that the command will create.
Add `/tenants/{id}` endpoint where the command will be generated.
Add unit tests. The `Tenant` has to be registered beforehand.

**Comment by stanislavgrujic** [comment]
What are necessary commands and events? :) Try to be more specific, since it may happen that it is not you who will work on the task, and there isn't enough information in it, in order to finish the task.

**Comment by MBarjaktarovic** [comment]
Updated the issue description.

**Comment by millevlada** [comment]
I miss some 'narrative' that explains the use case here. So, I'll try to fill the void myself ;)
Manager can be in charge of a lot of buildings. I think it is not pragmatic to expect that he himself register all the tenants users to a buildings, specially since that requires knowing all the data like emails etc. It is maybe better scenario that manager registers the building with total number of apartments in it, and then let users register them self as tenants in particular building and apartment. Such registrations would require confirmation of manager before tenant could participate in any activities related to building.
So, instead of story given here, we might make this tasks breakdown:
1. Manager can register himself into system (as manager).
2. Manager can registers the building with total number of apartments.
3. Tenant can register himself into system (as tenant).
4. Tenant can assign himself for building/apartment. Such registration is initially inactive. 
5. Manager can overview tenant registrations for buildings/apartments, and approve inactive registration (single or for entire building at once).
6. Manager can reject tenant registrations for building/apartment, such registration becomes invalidated.
7. [???] As enhancement feature, we can allow multiple tenants to be assigned to same building/apartment.
8. Conversation between manager and tenant can be started even when tenant does not have valid registration for building apartment - can actually be used as communication channel when manager decides upon tenant/apartment registarations.

- Items 1, 3, 8 are already implemented.
- Item 2 would need small enhancement, for example command that updates the number of apartments in the building. It can be success if it is >= with highest existing apartment with assigned tenant, or fails otherwise. 
- Item 4, 5, 6 are main focus of this issue, and would require several commands/events, maybe even Saga for resolving the tenant apartment registration, since it might involve the conversations as well.

**Comment by millevlada** [comment]
done
